import os
os.system("color 0a")
os.system("cls")

print()
print("                 ██████╗██████╗  ██████╗  ██████╗ ██╗  ██╗███████╗     ██████╗ ██████╗ ██████╗ ██████╗  (R)")
print("                ██╔════╝██╔══██╗██╔═══██╗██╔═══██╗██║ ██╔╝██╔════╝    ██╔════╝██╔═══██╗██╔══██╗██╔══██╗")
print("                ██║     ██████╔╝██║   ██║██║   ██║█████╔╝ ███████╗    ██║     ██║   ██║██████╔╝██████╔╝")
print("                ██║     ██╔══██╗██║   ██║██║   ██║██╔═██╗ ╚════██║    ██║     ██║   ██║██╔══██╗██╔═══╝ ")
print("                ╚██████╗██║  ██║╚██████╔╝╚██████╔╝██║  ██╗███████║    ╚██████╗╚██████╔╝██║  ██║██║     ")
print("                ╚═════╝╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚══════╝     ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚═╝     ")
print()
print("AIRLOCK MANAGEMENT".center(120))
print()
print("                                                    SELECT AN OPTION")
print()
print("                                              [1] - View Airlocks")
print("                                              [2] - Enable/Diable Airlocks")
print("                                              [3] - System Logs")
print("                                              [4] - Emergency Override")
print("                                              [5] - Log Out")
print()
input("                                              >")